version: '3.7'
services:
  #NgInx
  nginx:
    container_name: dev_web
    restart: on-failure
    image: nginx:1.19.8
    volumes:
      - ./nginx/prod/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    ports:
      - "80:80"
    depends_on:
      - web
  #Backend
  web:
    container_name: dev_backend
    build: .
    restart: always
    env_file: dev.env
    command: gunicorn jetcontent.wsgi:application --bind 0.0.0.0:5000
    volumes:
      - .:/app
      - static_volume:/app/static
    depends_on:
      - db
  #Postgres
  db:
    container_name: dev_db
    image: postgres:12.0-alpine
    env_file: dev.env
    ports:
      - "5432:5432"
    volumes:
      - ./docker-compose/postgres/db_data:/var/lib/postgresql/data/

  #pgAdmin
  pgadmin:
    container_name: dev_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  #redis
  redis:
    container_name: dev_redis
    image: redis:3.0-alpine
    restart: always
    ports:
      - "6379:6379"

volumes:
  static_volume:
  postgres_data: