# Generated by Django 3.2.5 on 2021-11-14 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211114_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['title'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelTable(
            name='article',
            table='core_articles',
        ),
        migrations.AlterModelTable(
            name='site',
            table='core_sites',
        ),
    ]
