# Generated by Django 3.2.5 on 2021-11-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211114_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='prefix',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='Prefix'),
        ),
    ]
